### PR TITLE
[EDGE-2023] Fixing sample notebooks to not have circular reference symbols

### PR DESCRIPTION
**Pull request by snazzer**
See https://integrateai.atlassian.net/browse/EDGE-2023?focusedCommentId=23612 for context

### CODE REVIEW

**Review by luis-integrate — APPROVED** [review]
LGTM!

**Review by explizito — COMMENTED** [review]
Looks good!

**Comment by shaydchara** [comment]
Why did this go to `main`? It should have been on `develop` or the `release-platform` branch...

**Comment by snazzer** [comment]
> Why did this go to `main`? It should have been on `develop` or the `release-platform` branch...

Ah! wrong branch target. I will merge it to those branches if thats ok?

**Pull request merged**
